### ISSUE TITLE
Please license the game

### ISSUE THREAD

**Issue by ghost** [peacher5/mini-uno-game#1]
I and some other person was playing this game and it is very fun and the other person wants to put the game on there tilde server but the game needs to be licensed for them to do so, could you please license the game? I recommend a free license, please read this https://www.gnu.org/licenses/licenses.html but if it seems like too much work to read all that then you should use the expat license (AKA MIT license) becuse you can always license the game with a diffrent license latter (keep in mind that people can use the version of the game thay got with expat license under those terms and only latter releases will be under the new license)

**Comment by peacher5** [comment]
Thanks to everyone who interested in this game. I decided to choose MIT license for this project, so you guys can fork it and do whatever you like.
